name: build-macos

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          pip install pybind11 cmake

      - name: Configure
        run: |
          cmake -S . -B build \
            -DPYTHON_EXECUTABLE=$(which python) \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release -j4

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mac-python-so
          path: build/**/*.so
